#define LED_PIO		AT91C_BASE_PIOB		//adres kontrolera PIOB

#define LED_MASK	(AT91C_PIO_PB21|AT91C_PIO_PB25) 

#define LED_INIT	{LED_PIO->PIO_PER = LED_MASK; LED_PIO->PIO_OER = LED_MASK; LED_PIO->PIO_OWER = LED_MASK;}

#define LED1_EXT_SET		LED_PIO->PIO_SODR = AT91C_PIO_PB21  //zapalenie 1 diody
#define LED1_EXT_CLR		LED_PIO->PIO_CODR = AT91C_PIO_PB21	//zgaszenie 1 diody

#define LED2_EXT_SET		LED_PIO->PIO_SODR = AT91C_PIO_PB25  //zapalenie 1 diody
#define LED2_EXT_CLR		LED_PIO->PIO_CODR = AT91C_PIO_PB25	//zgaszenie 1 diody


// Klawisz
#define LEFT_KEY_DOWN (((AT91C_BASE_PIOB->PIO_PDSR) & AT91C_PIO_PB24)==0)
#define LED_BCK_TGL (AT91C_BASE_PIOB->PIO_ODSR=AT91C_BASE_PIOB->PIO_ODSR ^ AT91C_PIO_PB20)
